### ISSUE TITLE
Demo Version Login and Password incorrect.

### ISSUE THREAD

**Issue by ashishkharcheiu** [humansis/offline_app#11]
@Suppress("ConstantConditionIf")
        @SuppressLint("SetTextI18n")
        if (BuildConfig.FLAVOR == "demo") {
            et_username.setText("demo@humansis.org")
            et_password.setText("Update987")
        }

The login details provided in the code does not seem to work.

What are the correct details for demo? and is there a source code for release version?

**Comment by Happs80** [comment]
Hi,

Apologies for the slow reply.

Please email info@humansis.org for login details if you require more info.

Also, the demo version of the app is essentially a copy of the release version.
