### ISSUE TITLE
App Crashing On Some Smartphones

### ISSUE THREAD

**Issue by Happs80** [humansis/offline_app#3]
FSamsung Galaxy S5. Android ver 6.16

Updated to Ver 0.10

Directly after credentials are supplied, the app crashes completely and displays 'App has Stopped' error message.

![image](https://user-images.githubusercontent.com/31128624/73542435-fc4b4180-4434-11ea-82d4-3ee8cbf27d64.png)

![image](https://user-images.githubusercontent.com/31128624/73542443-00775f00-4435-11ea-8830-e08702d3b676.png)

![image](https://user-images.githubusercontent.com/31128624/73542450-04a37c80-4435-11ea-97cf-b56745918789.png)

**Comment by haluzpav** [comment]
Let us know if app still crashes on start even on version 1.0.0. Crash log would be the best.

**Comment by Happs80** [comment]
Not sure if exactly same issues, but my phone now has crashed a couple of times, just running in the background. See attached report.

**Comment by Happs80** [comment]
[ACRA-report.zip](https://github.com/humansis/offline_app/files/4193538/ACRA-report.zip)

**Comment by haluzpav** [comment]
That sounds like a different issue. I already created separate issue for the crashlog you sent. #4

**Comment by Happs80** [comment]
Looks fixed.
