### ISSUE TITLE
Duplicate Assignments Found

### ISSUE THREAD

**Issue by Happs80** [humansis/offline_app#6]
In the app, it appears as though double assignments have occurred.

![Screenshot_20200221-070921](https://user-images.githubusercontent.com/31128624/75008728-18ad2d80-5479-11ea-803c-55b9e61ca509.jpg)

**Comment by haluzpav** [comment]
This beneficiary actually has 2 assigned booklets. Truncated response from `https://api.bmstaging.info/api/wsse/distributions/70/beneficiaries`

``` json
{
  "id": 17846,
  "beneficiary": {
    "id": 7523
  },
  "booklets": [
    {
      "id": 16183,
      "code": "15401-16574-16183",
      "currency": "SYP",
      "status": 1,
      "vouchers": []
    },
    {
      "id": 16372,
      "code": "15401-16574-16372",
      "currency": "SYP",
      "status": 1,
      "vouchers": []
    }
  ]
}
```

Web front-end shows only one, Android shows both. Both use the same data.

Does it make sense that one beneficiary has 2 booklets? How should we deal with it?

**Comment by Happs80** [comment]
So we have discovered this was a mistake by the team. They have assigned multiple booklets to one household.

But regardless, it is a good thing to pick up.

As i defined it to the back end developers, the most recent write to the db should be the 'correct one', in case there are conflicts during offline sync.

However i didnt know they were also keeping the old record of voucher assignments.

The app should only display the most recent i believe, we should be the top record. 

Is that possible?

**Comment by haluzpav** [comment]
We don't know which one is the most recent one. There's no timestamp etc. It seems the web might be showing just the first one. 
<img width="799" alt="Screen Shot 2020-02-24 at 14 39 09" src="https://user-images.githubusercontent.com/24211726/75157013-94c2a200-5713-11ea-8243-5da3101751d3.png">

**Comment by Happs80** [comment]
is it at all possible to just select the first? presuming the json file orders on write...

**Comment by haluzpav** [comment]
Sure we can. But it feels like this should be solved in backend.

**Comment by Happs80** [comment]
yes. sure. i wouldn't say its bug necessarily though. just the only way to deal with conflict resolution i think.

**Comment by Happs80** [comment]
Further discussion with the team. Agreed that it would be better to leave as is from the app side. Fix must come from back end. Thanks for advice.
